#! /bin/sh

# Move --kube-context option at the end for easier parsing
cmd=$(echo "$@" | sed 's/\(--kube-context [a-zA-Z0-9\-]* \)\(.*\)/\2 \1/g')
arg=$(echo "${cmd}" | cut -d " " -f1)

# helm secrets only supports a few helm commands
if [ ${arg} = "template" ] || [ ${arg} = "install" ] || [ ${arg} = "upgrade" ] || [ ${arg} = "lint" ] || [ ${arg} = "diff" ]
then 
    # Helm secrets add some useless outputs to every commands including template, namely
    # 'remove: <secret-path>.dec' for every decoded secrets.
    # As argocd use helm template output to compute the resources to apply, these outputs
    # will cause a parsing error from argocd, so we need to remove them.
    # We cannot use exec here as we need to pipe the output so we call helm in a subprocess and
    # handle the return code ourselves.
    out=$(helm.bin secrets $cmd) 
    code=$? 
    if [ $code -eq 0 ]; then
        # printf insted of echo here because we really don't want any backslash character processing
        printf '%s\n' "$out" | sed -E "/^removed '.+\.dec'$/d"      
        exit 0
    else
        exit $code
    fi
else
    # helm.bin is the original helm binary
    exec helm.bin $cmd
fi
